AMASADOSUR/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path, include
from ventas import views
from abastecimiento import views
from django import forms
from django.conf import settings
#from  import views


urlpatterns = [

    path(r'', views.index, name="index"),
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path(r'ventas/', include(('ventas.urls', 'ventas'), namespace='ventas')),
    path('admin/', admin.site.urls),
    path(r'abastecimiento/', include(('abastecimiento.urls', 'abastecimiento'), namespace='abastecimiento')),
    path(r'logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

]

abastecimiento/urls.py
from abastecimiento import views

from django.urls import path, include, reverse, reverse_lazy
from django.views.generic.list import ListView

app_name = 'abastecimiento'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'productos/', views.ProductoList.as_view(), name='productos'),
    path(r'compra/', views.compra, name='compra'),
    path(r'compra/nueva/nueva', views.nueva, name='nueva'),
    path(r'compra/nueva/nueva/add', views.agrega_detalle, name='agrega_detalle'),
    path(r'compra/nueva', views.verifica, name='verifica'),
    path(r'producto/menu_buscar', views.menu_buscar, name='menu_buscar'),
    path(r'producto/buscar', views.buscar, name='buscar'),

    path(r'test/', views.test, name='test'),




    # path(r'reporte/boletas/detalle/<int:id>', views.detalle_boleta, name='detalle_boleta'),
    ]

ventas/urls.py
from . import views
from ventas import views
from django.urls import path, include

app_name='ventas'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'nueva/', views.nueva, name='nueva'),
    #path(r'nueva/boleta/', views.boleta, name='boleta'),
    path(r'nueva/add', views.detalleadd, name='add'),
    path(r'nueva/menu2/', views.menu2, name='menu2'),    
    path(r'abrircaja/', views.abrircaja, name='abrircaja'),
    path(r'nueva/lista/', views.VentaList.as_view(), name='ventalist'),

    path(r'nueva/lista/pagar', views.pagar, name='pagar'),
    path(r'nueva/lista/formapago', views.formapago, name='formapago'),
    #path(r'abrircaja/formapago', views.formapago, name='formapago'),
    #path(r'nueva/formapago', views.formapago, name='formapago'),
    path(r'nueva/lista/documento', views.tipodocumento, name='tipodocumento'),
    path(r'nueva/lista/verifica', views.verifica, name='verifica'),
    path(r'nueva/lista/registrocliente', views.registracliente, name='registracliente'),
    path(r'cerrarcaja/', views.cerrarcaja, name='cerrarcaja'),
    path(r'cerrarcaja/arqueo', views.arqueo, name='arqueo'),
    path(r'cierracaja/', views.cierracaja, name='cierracaja'),

    path(r'estadisticas/', views.estadisticas, name='estadisticas'),
    path(r'reporte/boletas/', views.vista_boleta, name='vista_boleta'),
    path(r'reporte/boletas/cierre', views.vista_boleta_vivo, name='vista_boleta_vivo'),
    path(r'reporte/facturas/', views.vista_factura, name='vista_factura'),
    path(r'reporte/boletas/detalle/<int:id>', views.detalle_boleta, name='detalle_boleta'),
    path(r'reporte/facturas/detalle/<int:id>', views.detalle_factura, name='detalle_factura'),
    path(r'exito/', views.exito, name='exito'),
    path(r'test/', views.test, name='test'),
    
]

    # path(r'reporte/boletas/lista', views.detalle_boleta, name='detalle_boleta'),

    # https://stackoverflow.com/questions/7217811/query-datetime-by-todays-date-in-django

abastecimiento/models.py
from django.db import models
from django.conf import settings


class Proveedor(models.Model):
    rut = models.CharField(max_length=10, blank=False, null=False)
    nombre = models.CharField(max_length=100, blank=False, null=False)
    direccion = models.CharField(max_length=100, blank=False, null=False)
    telefono = models.IntegerField()
    email = models.EmailField(max_length=254)
    class Meta:
        verbose_name_plural = "Proveedores"

        def __str__(self):
            return str(self.rut)


class Producto(models.Model):
    codigo_barras = models.IntegerField()
    nombre = models.CharField(max_length=10, blank=False, null=False)
    descripcion = models.CharField(max_length=30, blank=False, null=False)
    precio_venta_unitario = models.IntegerField(default=0)
    ppp = models.IntegerField(editable=False, default=0)
    stock = models.IntegerField(default=0, editable=False)
    margen = models.IntegerField(default=20)


    def __str__(self):
        return self.nombre


class Compra(models.Model):
    documento = models.CharField(max_length=20, blank=True, null=True)
    fecha = models.DateField()
    proveedor = models.ForeignKey(
        'Proveedor', related_name='proveedores', on_delete=models.PROTECT)
    total = models.IntegerField(blank=True,null=True)
    producto = models.ManyToManyField('Producto', through='DetalleCompra')
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,blank=True, null=True)

    def __str__(self):
        return str(self.id)


class DetalleCompra(models.Model):
    id_compra = models.ForeignKey('Compra', related_name='compra', on_delete=models.CASCADE)
    id_producto = models.ForeignKey(
        "Producto", related_name='producto', on_delete=models.CASCADE)
    lote = models.CharField(max_length=30, blank=True, null=True)
    fecha_vencimiento = models.DateField()
    cantidad = models.IntegerField()
    precio_compra_unitario = models.IntegerField()

    class Meta:
        ordering = ["id"]
        verbose_name_plural = "Detalle de Compras"
        verbose_name = "Detalle de Compra"

        def __str__(self):
            return self.id

abastecimiento/forms.py
from django import forms
from .models import Producto,Compra,DetalleCompra

abastecimiento/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Sum
from django.db.models import Q,F
from django.db.models import IntegerField



from .models import Producto, Proveedor, Compra, DetalleCompra


@login_required
def index(request):
    return render(request, 'ventas/menu2.html')




@method_decorator(login_required, name='dispatch')
class ProductoList(ListView):
    model = Producto
    paginate_by = 20
    order_by = 'nombre'
    template_name = 'abastecimiento/productos.html'
    context_object_name = 'productos'





class CrearCompra(CreateView):
    pass


    

@login_required
class ListadoCompras(ListView):
    model = Compra
    template_name = 'abastecimiento/compras.html'
    context_object_name = 'compras'


@login_required
def compra(request):
    return render(request, "abastecimiento/compra.html")

@login_required
def nueva(request):
    if request.method == "POST":
        documento=request.POST.get('dcto')
        proveedor = Proveedor.objects.get(rut=request.POST.get('rut'))

        try:
            Compra.objects.get(documento=documento,proveedor=proveedor)
            mesj="Documento ya ingresado"
            return render(request,'ventas/info.html',{'mesj': mesj})
        except Compra.DoesNotExist:
            documento = request.POST.get('dcto')
            fecha=request.POST.get('fecha')
            proveedor=Proveedor.objects.get(rut=request.POST.get('rut'))
            usuario=request.user
            nueva_compra=Compra(documento=documento,fecha=fecha,proveedor=proveedor,usuario=usuario)
            nueva_compra.save()
            print(Compra.objects.latest('id'))


            context={
                'documento': documento,
                'fecha': fecha,
                'dcto': documento,
                'rut': proveedor.rut,
                'nombre': proveedor.nombre,
                'id': Compra.objects.latest('id'),
                'usuario': usuario,
            }
        return render(request,'abastecimiento/compra.html',context)

@login_required
def agrega_detalle(request):
    if request.method == 'POST':
        
        id_compra2 = request.POST.get('id_compra')
        id_2 = Compra.objects.get(id=id_compra2)
        codigo=request.POST.get('codigo')
        try:
            producto = Producto.objects.get(codigo_barras=codigo)
        except Producto.DoesNotExist:
            msj2="Producto No existe"
            return render(request,'ventas/venta.error.html', {'msj2': msj2})
            
        #consulta si ya se ingresó el producto
        try:
            consulta = DetalleCompra.objects.get(id_producto=producto.id,id_compra=id_compra2)
            msj2 = "Producto ya ingresado"
            context ={
                'msj2': msj2,
            }
            return render(request, 'ventas/venta.error.html', context)
        
        except DetalleCompra.DoesNotExist:
            print(producto.id)
            lote = request.POST.get('lote')
            fecha_vencimiento = request.POST.get('fecha_vencimiento')
            cantidad = request.POST.get('cantidad')
            precio_compra_unitario = request.POST.get('precio')
            nuevo_detalle = DetalleCompra.objects.create(id_compra=id_2, id_producto=producto, lote=lote,fecha_vencimiento = fecha_vencimiento, cantidad = cantidad,precio_compra_unitario = precio_compra_unitario)
            compras_productos = DetalleCompra.objects.filter(id_producto=producto)
            q = 0
            p = 0
            ppp = 0
            for compra_producto in compras_productos:
                p += compra_producto.precio_compra_unitario * compra_producto.cantidad
                print("p")
                print(p)
                q += compra_producto.cantidad
                print("q")
                print(q)
                
                ppp = p/q
                print("ppp")
                print(ppp)
            
            actualiza_producto = Producto.objects.get(id=producto.id)
            actualiza_producto.ppp=ppp
            print(actualiza_producto.stock)
            cant = actualiza_producto.stock
            precio = ppp+(ppp*0.19)
            precio = precio + (precio*(actualiza_producto.margen/100))
            #precio = precio+(precio*0.19)
            print("precio" )
            print(precio)
            #cant = Producto.objects.get(id=producto.id)['stock']
            
            cant = cant + int(cantidad)
            actualiza_producto.stock = cant
            actualiza_producto.precio_venta_unitario = precio
            """ actualiza_producto.precio_venta_unitario = ((actualiza_producto.ppp + (actualiza_producto.ppp*0.19))
            actualiza_producto.precio_venta_unitario +=(actualiza_producto.ppp *(actualiza_producto.margen/100)) 
            actualiza_producto.precio_venta_unitario += actualiza_producto.precio_venta_unitario*0.19 """
            actualiza_producto.save()

            detalles = DetalleCompra.objects.filter(id_compra=id_2.id)
            documento = request.POST.get('dcto')
            proveedor = Proveedor.objects.get(rut=request.POST.get('rut'))
            fecha=request.POST.get('fecha')
            print(fecha)
            usuario=request.user

            total = DetalleCompra.objects.filter(id_compra=id_2.id).aggregate(suma=Sum(F('cantidad')*F('precio_compra_unitario')))
            compra = Compra.objects.get(id=id_2.id)
            compra.total = total['suma']
            compra.save()
            

            context={
                    'suma': total['suma']+(total['suma']*0.19),
                    'detalles': detalles,
                    'fecha': fecha,
                    'dcto': documento,
                    'rut': proveedor.rut,
                    'nombre': proveedor.nombre,
                    'id': id_2.id,
                    'usuario': usuario,
                }
            return render(request, 'abastecimiento/compra.html', context)

@login_required
def verifica(request):
    if request.method=="POST":
        rut_proveedor = request.POST['rut']
        print(rut_proveedor)
        try:
            proveedor = Proveedor.objects.get(rut=rut_proveedor)
            print(proveedor.nombre)
            
            context={
                'nombre': proveedor.nombre,
                'rut': proveedor.rut,
                'usuario': request.user
            }
            return render(request, 'abastecimiento/compra.html', context)
        except Proveedor.DoesNotExist:
            proveedor=None
            mesj = "Proveedor no existe,redirigiendo"
            context={
                'mesj2': mesj
            }
            return render(request,'ventas/info.html',context)

@login_required
def test(request):
    return render(request, 'abastecimiento/test.html')




def menu_buscar(request):
    return render(request,'abastecimiento/buscar.html')

def buscar(request):

        ingreso = request.POST.get('producto')
        print(ingreso)
        try:
            producto = Producto.objects.get(codigo_barras=ingreso)

            return render (request,'abastecimiento/buscar.html',{'producto': producto})

        except Producto.DoesNotExist:
            msj = "Producto no existe en Base de Datos"

            return render(request,'abastecimiento/buscar.html',{'msj':msj})

templates/abastecimiento/buscar.html
{% extends "base.html"%}

{% block estilo %}{% endblock %}

{% load staticfiles %}

{% block tittle %}Buscar Producto{% endblock %}
{% block content %}

    <div class = "row">
    <div class = "col-md-3"></div>
    <div class = "col-md-6">

        {% if msj %}
                <div class="alert alert-danger text-center" role="alert">
                    {{msj}}
                </div>

                <script type="text/javascript">
                    function Redirect2()
                        {
                            window.history.back();
                        }
                    setTimeout('Redirect2()', 1000);
                </script>



        {% elif producto %}
            <table class="table">
                <thead>
                  <tr>
                    <th>id</th>
                    <th>Nombre</th>
                    <th>Precio</th>
                  </tr>
                </thead>
            <tbody>

                  <tr>
                    <td>{{ producto.id}}</td>
                    <td>{{ producto.nombre }}</td>
                    <td>{{ producto.precio_venta_unitario }}</td>
                  </tr>

            </tbody>
            </table>

            <script type="text/javascript">
                    function Redirect2()
                        {
                            window.history.back();
                        }
                    setTimeout('Redirect2()', 2000);
                </script>

        {% else %}






        <form action = "buscar" method ="POST">
            {% csrf_token %}
            <div class="form-group">

                <label for="producto">Codigo Barras</label>
                <input type="text" class="form-control" id="producto" aria-describedby="ingrese codigo de barras" placeholder="Ingrese código" name="producto">
                <small id="producto" class="form-text text-muted">Ingrese el codigo de barrassss</small>
             </div>

            <button type="submit" class="btn btn-primary">Aceptar</button>
        </form>
        {% endif %}
    </div>


    <div class = "col-md-3"></div>
    </div>
    

{% endblock %}

templates/abastecimiento/compra.html
{% extends "base.html"%}

{% block estilo %}{% endblock %}

{% load staticfiles %}

{% block tittle %}Compra{% endblock %}
{% block content %}
    <div class="container-fluid">

        &nbsp
	<div class="row">
		<div class="col-md-2">
        </div>


        {% if rut and fecha is None %}

            <div class="col-md-4">
            
            <form action="{% url 'abastecimiento:nueva' %}" method="post">{% csrf_token %}
                <div class="container">
                    <div class="form-row">

                        <label for="rut" class="col-md-3 col-form-label-sm align-content-end">Rut Proveedor</label>
                        <div class="col-7">
                            <input type="text" class="form-control form-control-sm" id="rut" name="rut" placeholder="{{ rut }}" value="{{ rut }}" readonly>
                        </div>

                        <label for="nombre" class="col-md-3 col-form-label-sm">Nombre Provee.</label>
                        <div class="col-7">
                            <input type="text" class="form-control form-control-sm" id="nombre" name="nombre" placeholder={{ nombre }} readonly>
                        </div>

                        <label for="usuario" class="col-md-3 col-form-label-sm ">Usuario</label>
                        <div class="col-md-7">
                            <input type="text" class="form-control form-control-sm" id="usuario" name="usuario" placeholder={{ usuario }} readonly>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-4">

                <div class="container">
                    <div class="form-row">
                        <label for="dcto" class="col-md-5 col-form-label-sm text-right">Dcto.Compra</label>
                        <div class="col-md-7">
                            <input type="text" class="form-control form-control-sm" id="dcto" name="dcto" required>
                        </div>

                        <label for="fecha" class="col-md-5 col-form-label-sm text-right">Fecha</label>
                        <div class="col-md-7">
                            <input type="date" class="form-control form-control-sm" id="fecha" name="fecha" required>
                        </div>
                        <div class="col offset-md-8">
                                <button type="submit" class="btn btn-primary">Registra Compra</button>
                        </div>


                    </div>
                </div>
            </form>
            </div>




        {% elif rut and fecha %}
        
            <div class="col-md-4">
            
                <form class="text-black-50" action="{% url 'abastecimiento:agrega_detalle' %}" method="post">{% csrf_token %}
                        <input type="hidden" name="id_compra" value="{{ id }}" readonly>
                            <div class="container">
                                <div class="form-row">

                                    <label for="rut" class="col-md-3 col-form-label-sm align-content-end">Rut Proveedor</label>
                                    <div class="col-7">
                                        <input type="text" class="form-control form-control-sm" id="rut" name="rut" value = {{ rut }} placeholder="{{ rut }}" readonly>
                                    </div>


                                    <label for="nombre" class="col-md-3 col-form-label-sm">Nombre Provee.</label>
                                    <div class="col-7">
                                        <input type="text" class="form-control form-control-sm" id="nombre" name="nombre" value = {{ nombre }} placeholder={{ nombre }} readonly>
                                    </div>

                                    <label for="usuario" class="col-md-3 col-form-label-sm ">Usuario</label>
                                    <div class="col-md-7">
                                        <input type="text" class="form-control form-control-sm" id="usuario" name="usuario" value = {{ usuario }} placeholder={{ usuario }} readonly>
                                    </div>

                                </div>
                            </div>


            </div>

            <div class="col-md-4">
                <div class="container">
                            <div class="form-row">
                                <label for="dcto" class="col-md-3 col-form-label-sm ">Dcto.Compra</label>
                                <div class="col-md-7">
                                    <input type="text" class="form-control form-control-sm" id="dcto" placeholder="{{ dcto }}" value= {{ dcto}} name="dcto"  readonly>
                                </div>

                                <label for="fecha" class="col-md-3 col-form-label-sm ">Fecha</label>
                                <div class="col-md-7">
                                    <input type="text" class="form-control form-control-sm" id="fecha" placeholder="{{ fecha }}" value = {{ fecha }} name="fecha"  readonly>
                                </div>
                            </div>
                </div>
            </div>


                    <div class="container-fluid">
                    &nbsp
                        <div class="form-row">
                            <div class="col-md-1">
                            </div>
                            <div class="col-md-2 text text-left text-black">
                                Código
                                <input id="codigo" name="codigo" type="number" placeholder="Ingrese Codigo" class="form-control input-lg" required autofocus >
                            </div>
                            <div class="col-md-1">
                                Cantidad
                                <input id="cantidad" name="cantidad" value="1" type="number" placeholder="1" class="form-control input-lg" autofocus >
                            </div>
                            <div class="col-md-1">
                                Precio Unit
                                    <input id="precio" name="precio" value="" type="number" class="form-control input-lg" required autofocus >
                            </div>
                            <div class="col-md-1">
                                Lote
                                    <input id="lote" name="lote" value="" type="text" class="form-control input-lg" required autofocus >
                            </div>
                            <div class="col-md-2">
                                F.Vencimiento
                                    <input id="fecha_vencimiento" name="fecha_vencimiento" value="" type="date" class="form-control input-lg" required autofocus >
                            </div>
                            <div class="col-md-1 text-light">
                                aceptar
                                    <button type="submit" class="btn btn-primary align-bottom"><span class="fa fa-barcode"></span> Agregar</button>
                            </div>
                            <div class="col-md-3 text text-black-50 h-auto">
                                <div class="text text-light">Total</div>
                                {% if suma %}
                                    <h2><strong>Total:</strong>{{suma}}</h2>
                                {% else %}
                                    <h2><strong>Total:</strong> 0</h2>
                                {% endif %}

                            </div>
                            <div class="col-md-1">
                            </div>
                        </div>
                    </div>
            <div class="col-md-1"></div>
            <div class="col-md-10">
            {% if mesj %}
                <div class="alert alert-warning" role="alert">
                    {{mesj}}
                </div>
            {% endif %}
            &nbsp
                <table class="table text text-center">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Producto</th>
                      <th scope="col">Lote</th>
                      <th scope="col">Fecha Vencimiento</th>
                      <th scope="col">Cantidad</th>
                      <th scope="col">Precio Unitario</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for detalle in detalles %}
                        <tr>
                            <th scope="row">{{detalle.id}}</th>
                            <td>{{detalle.id_producto}}</td>
                            <td>{{detalle.lote}}</td>
                            <td>{{detalle.fecha_vencimiento}}</td>
                            <td>{{detalle.cantidad}}</td>
                            <td>{{detalle.precio_compra_unitario}}</td>
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </div>
            </form>
            <div class="col-md-12 offset-10">
            <div onclick="javascript:window.location.href='{% url 'abastecimiento:compra' %}' ">
            <button type="submit" class="btn btn-primary align-bottom"><span class="fa fa-save"></span> Guardar</button> 
            </div>
            <div class="col-md-1">
               
            </div>



        {% else %}
         
            <div class="col-md-4">
            <div class="container">
                    <form action="{% url 'abastecimiento:verifica' %}" method="POST">{% csrf_token %}
                    <div class="form-row">
                        <label for="rut" class="col-md-3 col-form-label-sm text-right">Rut</label>
                        <div class="col-7">
                            <input type="text" class="form-control form-control-sm" id="rut" name="rut" required>
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-primary btn-sm">Verifica</button>
                        </div>
                        <label for="nombre" class="col-md-3 col-form-label-sm text-right">Nombre</label>
                        <div class="col-7">
                            <input type="text" class="form-control form-control-sm" id="nombre" name="nombre">
                        </div>

                    </div>
                    </form>

            </div>
        </div>
            <div class="col-md-4">
            <div class="container">
                <div class="form-row">
                    <label for="fecha" class="col-md-5 col-form-label-sm text-right">Fecha</label>
                    <div class="col-md-7">
                        <input type="date" class="form-control form-control-sm" id="fecha" name="fecha" placeholder="" readonly>
                    </div>
                    <label for="dcto" class="col-md-5 col-form-label-sm text-right">Dcto.Compra</label>
                    <div class="col-md-7">
                        <input type="text" class="form-control form-control-sm" id="dcto" name="dcto" readonly>
                    </div>

                </div>
            </div>

        {% endif %}


        <div class="col-md-2">
		</div>


    </div>
    </div>
    </div>


{% endblock %}

{% block footer %}{% endblock %}

templates/abastecimiento/compra1.html
{% extends "base.html"%}
{% block estilo %}{% endblock %}

{% load staticfiles %}

{% block tittle %}Compra{% endblock %}
{% block content %}
    <div class="container-fluid">
    <form action="/" method="POST">
        {% csrf_token %}

        &nbsp;
	<div class="row">
		<div class="col-md-3">
		</div>
		<div class="col-md-3">
            <div class="container">

                    <div class="form-row">
                        <label for="rut" class="col-md-3 col-form-label-sm align-content-end">Rut</label>
                        <div class="col-7">
                            <input type="text" class="form-control form-control-sm" id="rut" name="rut" required>
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-primary">Verifica</button>
                        </div>
                        <label for="nombre" class="col-md-3 col-form-label-sm">Nombre</label>
                        <div class="col-7">
                            <input type="text" class="form-control form-control-sm" id="nombre" name="nombre">
                        </div>
                         <label for="direccion" class="col-md-3 col-form-label-sm">Direccion</label>
                        <div class="col-7">
                            <input type="text" class="form-control form-control-sm" id="direccion" name="direccion">
                        </div>
                    </div>

            </div>
        </div>


        <div class="col-md-3">
            <div class="container">
                <div class="form-row">
                    <label for="email" class="col-md-3 col-form-label-sm">E-mail</label>
                    <div class="col-md-7">
                        <input type="email" class="form-control form-control-sm" id="email" name="email">
                    </div>
                    <label for="telefono" class="col-md-3 col-form-label-sm">Telefono</label>
                    <div class="col-md-7">
                        <input type="number" class="form-control form-control-sm" id="telefono" name="telefono">
                    </div>
                    <label for="fecha" class="col-md-3 col-form-label-sm">Fecha</label>
                    <div class="col-md-7">
                        <input type="date" class="form-control form-control-sm" id="fecha" name="fecha">
                    </div>
                 <!--   <div class="col-md-10 offset-md-7">
                       <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                 --->
                </div>
            </div>
        </div>
        <div class="col-md-3">
		</div>
    </div>

        <div class="row">
            <div class="col-md-1">
		    </div>
		    <div class="col-md-3">
		    </div>
		    <div class="col-md-1">
		    </div>
		    <div class="col-md-1">
		    </div>
		    <div class="col-md-3">
		    </div>
		    <div class="col-md-1">
		    </div>
		    <div class="col-md-1">

		</div>
		<div class="col-md-3 ">
		</div>
		<div class="col-md-3 border border-0">

            <form class="form-row align-items-center text text-center text-black-50" action="/ventas/nueva/add" method="POST">
                {% csrf_token %}
                Codigo
                <input id="textinput" name="textinput" type="number" placeholder="Ingrese Codigo" class="form-control input-lg"
                       required="" autofocus >
		</div>

        <div class="col-md-1 text-black-50">
                Cantidad
                <input id="cantidad" name="cantidad" value="1" type="number" placeholder="1" class="form-control input-lg" autofocus >
		</div>

        <div class="col-md-1 text-black-50">
                Precio Unit
                <input id="precio" name="precio" value="" type="number" class="form-control input-lg" autofocus >
		</div>
		<div class="col-md-1 text-light ">
            aceptar
                <button type="submit" class="btn btn-primary align-bottom"><span class="fa fa-barcode"></span> Aceptar</button>

		</div>
            </form>
		<div class="col-md-3 text text-center text-black-50 h-auto">
            <div class="text text-light">Total</div>
            <h2><strong>Total:</strong> {{suma}}</h2>


		</div>
		<div class="col-md-1">
		</div>
	</div>

















    </form>
    </div>





{% endblock %}

{% block footer %}
{% endblock %}

templates/abastecimiento/producto_add.html
{% extends 'base.html'%}
{% load staticfiles %}
{% block content %}

    <div class="form-group">
    <form method="POST">
        {% csrf_token %}

            <label for="address" class="col-sm-3 control-label">Nombre:</label>{{ form.nombre }}
            {{ form.as_p }}

    <button type="submit" class="btn btn-danger">Guardar</button>
        </div>
    </form>


{% endblock %}