AMASADOSUR/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path, include
from ventas import views
from abastecimiento import views
from django import forms
from django.conf import settings
#from  import views


urlpatterns = [

    path(r'', views.index, name="index"),
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path(r'ventas/', include(('ventas.urls', 'ventas'), namespace='ventas')),
    path('admin/', admin.site.urls),
    path(r'abastecimiento/', include(('abastecimiento.urls', 'abastecimiento'), namespace='abastecimiento')),
    path(r'logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

]

abastecimiento/urls.py
from abastecimiento import views

from django.urls import path, include, reverse, reverse_lazy
from django.views.generic.list import ListView

app_name = 'abastecimiento'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'productos/', views.ProductoList.as_view(), name='productos'),
    path(r'compra/', views.compra, name='compra'),
    path(r'compra/nueva/nueva', views.nueva, name='nueva'),
    path(r'compra/nueva/nueva/add', views.agrega_detalle, name='agrega_detalle'),
    path(r'compra/nueva', views.verifica, name='verifica'),
    path(r'producto/menu_buscar', views.menu_buscar, name='menu_buscar'),
    path(r'producto/buscar', views.buscar, name='buscar'),

    path(r'test/', views.test, name='test'),




    # path(r'reporte/boletas/detalle/<int:id>', views.detalle_boleta, name='detalle_boleta'),
    ]

ventas/urls.py
from . import views
from ventas import views
from django.urls import path, include

app_name='ventas'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'nueva/', views.nueva, name='nueva'),
    #path(r'nueva/boleta/', views.boleta, name='boleta'),
    path(r'nueva/add', views.detalleadd, name='add'),
    path(r'nueva/menu2/', views.menu2, name='menu2'),    
    path(r'abrircaja/', views.abrircaja, name='abrircaja'),
    path(r'nueva/lista/', views.VentaList.as_view(), name='ventalist'),

    path(r'nueva/lista/pagar', views.pagar, name='pagar'),
    path(r'nueva/lista/formapago', views.formapago, name='formapago'),
    #path(r'abrircaja/formapago', views.formapago, name='formapago'),
    #path(r'nueva/formapago', views.formapago, name='formapago'),
    path(r'nueva/lista/documento', views.tipodocumento, name='tipodocumento'),
    path(r'nueva/lista/verifica', views.verifica, name='verifica'),
    path(r'nueva/lista/registrocliente', views.registracliente, name='registracliente'),
    path(r'cerrarcaja/', views.cerrarcaja, name='cerrarcaja'),
    path(r'cerrarcaja/arqueo', views.arqueo, name='arqueo'),
    path(r'cierracaja/', views.cierracaja, name='cierracaja'),

    path(r'estadisticas/', views.estadisticas, name='estadisticas'),
    path(r'reporte/boletas/', views.vista_boleta, name='vista_boleta'),
    path(r'reporte/boletas/cierre', views.vista_boleta_vivo, name='vista_boleta_vivo'),
    path(r'reporte/facturas/', views.vista_factura, name='vista_factura'),
    path(r'reporte/boletas/detalle/<int:id>', views.detalle_boleta, name='detalle_boleta'),
    path(r'reporte/facturas/detalle/<int:id>', views.detalle_factura, name='detalle_factura'),
    path(r'exito/', views.exito, name='exito'),
    path(r'test/', views.test, name='test'),
    
]

    # path(r'reporte/boletas/lista', views.detalle_boleta, name='detalle_boleta'),

    # https://stackoverflow.com/questions/7217811/query-datetime-by-todays-date-in-django

ventas/models.py
from django.db import models
from datetime import date
from django.conf import settings
from django.db import models
from abastecimiento.models import Producto


class Cliente(models.Model):
    rut = models.IntegerField(null=False, blank=False)
    nombre = models.CharField(max_length=100, null=False, blank=False)
    direccion = models.CharField(max_length=100, null=False, blank=False)
    def __str__(self):
        return str(self.nombre)

class Caja(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,blank=True, null=True)
    hora_a = models.DateTimeField(blank=True)
    hora_c = models.DateTimeField(blank=True, null=True)
    estado = models.CharField(max_length=10)
    monto_inicial = models.IntegerField()
    monto_final = models.IntegerField(blank=True, null=True)
    caja_modulo = models.CharField(max_length=20, null=False, blank=False)
    def __str__(self):
        return (self.estado)

class Venta(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=True)
    total = models.IntegerField(blank=True, null=True)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,blank=True, null=True)
    producto = models.ManyToManyField("abastecimiento.Producto", through='DetalleVenta')
    forma_pago = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return str(self.id)
   
class DetalleVenta(models.Model):
    id_detalleventa = models.AutoField(primary_key=True)
    id_venta = models.ForeignKey('Venta', on_delete=models.CASCADE)
    id_producto = models.ForeignKey('abastecimiento.Producto', on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio_venta_unitario = models.IntegerField()

    class Meta:
        ordering = ["id_venta"]
        verbose_name = 'Detalle de Ventas'
        verbose_name_plural = 'Detalle de Ventas'

        def __str__(self):
            return str(self.id_detalleventa)
            

class Factura(models.Model):
    id_venta = models.ForeignKey('Venta', on_delete=models.CASCADE)
    id_cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.id)


class Boleta(models.Model):
    id_venta = models.ForeignKey('Venta', on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.id)

ventas/forms.py
from django import forms
from .models import Cliente 



class RegCliente(forms.Form):
     rut = forms.IntegerField()
     nombre = forms.CharField(max_length=100)
     direccion = forms.CharField(max_length=100)

ventas/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect,HttpRequest
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from abastecimiento.models import DetalleCompra
from .models import Venta, Producto, DetalleVenta, Boleta, Factura, Cliente, Caja
from django.views.generic import ListView
from django.db.models import Q,F
from django.db.models import Sum, IntegerField
from django.shortcuts import render_to_response
from django.template import RequestContext
from .forms import RegCliente
from django.contrib.auth import get_user
from datetime import date, datetime






@login_required 
def index(request):
        return render(request, 'ventas/menu.html')

# @login_required
# def nueva2(request):

#         return render(request, 'ventas/nueva.html')

@login_required
def nueva(request):
        try:
                usuario = get_user(request)
                caja = Caja.objects.get(usuario=usuario,estado="abierta")
                print(caja)
                hoy=datetime
                print(caja.hora_a)
                if caja.hora_a.date()<datetime.now().date():
                        mesj="Caja no cerrada la ultima jornada. Por favor cerrar"
                        context={
                                'usuario': usuario,
                                'fecha': str(datetime.now()),
                                'caja': caja.caja_modulo,
                                'mesj': mesj,
                        } 
                        return render(request,'ventas/cerrarcaja.html', context)

                nueva_venta = Venta(usuario=request.user)
                nueva_venta.save()
                codigo_venta = Venta.objects.latest('id')
                print(codigo_venta)
                return render(request, 'ventas/detalleventa_list.html')

        except Caja.DoesNotExist:
                caja = None
                
                mesj = "¡Por favor abrir caja!"
                usuario=get_user(request)
                fecha = datetime.now()
                caja = request.META.get('REMOTE_ADDR')

                context = {
                        'msj': mesj,
                        'usuario': usuario,
                        'fecha': fecha.strftime('%Y-%m-%d %H:%M'),
                        'caja': caja
                }
                
                return render(request,'ventas/nocaja.html', context)
 
@login_required
def boleta(request):

    if request.method == 'POST':
        nueva_venta = Venta(usuario=request.user)
        nueva_venta.save()
        codigo_venta = Venta.objects.latest('id')
        print(codigo_venta)
    return render(request, 'ventas/venta.html')

@login_required
def detalleadd(request):

    if request.method == 'POST':  
        
        try:
                de_producto = Producto.objects.get(codigo_barras=request.POST.get('textinput'))
        except Producto.DoesNotExist:
                de_producto = None
                msj="Producto No existe"
                return render(request,'ventas/venta.error.html', {'msj': msj})

        flotante = (request.POST['textinput'])
        de_venta = Venta.objects.last()
        print(de_venta.id)
        print(de_producto.id)      
        # consulta para saber si hay mas de este mismo producto
        obj = DetalleVenta.objects.filter(id_producto=de_producto.id, id_venta=de_venta.id).first()
        
        # query = DetalleVenta.objects.filter(id_producto = flotante, id_venta = de_venta).count()
        precio = Producto.objects.get(codigo_barras=flotante).precio_venta_unitario
        
        if obj is None:
            det_venta = DetalleVenta()
            det_venta.id_producto=de_producto
            det_venta.id_venta=de_venta
            cero = request.POST.get('cantidad')
            if cero=='':
                det_venta.cantidad = 1
            else:
                det_venta.cantidad = request.POST.get('cantidad')
                det_venta.precio_venta_unitario = precio
                det_venta.save()
        else:
            det_venta = DetalleVenta.objects.get(id_producto=de_producto, id_venta=de_venta)
            cero = request.POST.get('cantidad')
            if cero=='':
                det_venta.cantidad += 1
            else:
                det_venta.cantidad += int(request.POST.get('cantidad'))
            det_venta.save()

        print(de_producto.nombre)
        print(precio)
        print(det_venta.cantidad)
        # print((det_venta.cantidad * det_venta.precio_venta))
        total2 = DetalleVenta.objects.filter(id_venta=Venta.objects.latest('id')).aggregate(suma=Sum(F('precio_venta_unitario')*F('cantidad')))
        print("total consulta")
        de_venta.total = total2["suma"]+(total2["suma"]*0.19)
        print(total2["suma"])
        contador = len(total2)
        de_venta.save()

        subtotal = Venta.objects.last()
        return HttpResponseRedirect('lista/')

@login_required
def formapago(request):
    if request.method == 'POST':
        forma = request.POST.get('exampleRadios')
        print("esta el la forma")
        print(forma)
        de_venta = Venta.objects.last()
        if forma =='option1':               
                de_venta.forma_pago = 'Efectivo'
                #nueva_boleta = Boleta(id_venta=Venta.objects.latest('id'))
        else:
                de_venta.forma_pago = 'Tarjeta'

        de_venta.save()
        
        tipo = request.POST.get('fp')
        print("esta es el tipo")
        print(tipo)
        if tipo == "boleta":
            nueva_boleta = Boleta(id_venta=Venta.objects.latest('id'))
            nueva_boleta.save()
            boleta2 = Boleta.objects.all().last()
            print("esta es la boleta")
            print(boleta2.id)
            venta = Boleta.objects.latest('id').id_venta
            print("esta es la venta")
            print(venta)
            detalles = DetalleVenta.objects.filter(id_venta=venta).values('id_producto','cantidad')
            print(detalles)
            for detalle in detalles:
                #instance.id_producto.stock += instance.cantidad
                stock_actual=Producto.objects.get(id=detalle['id_producto']).stock
                print(stock_actual)
                #producto = Producto.objects.get(id=detalle['id_producto']).stock-=detalle['cantidad']
                producto = Producto.objects.get(id=detalle['id_producto'])
                producto.stock -= detalle['cantidad']
                producto.save()

            # return render(request, 'ventas/exito.html', {'boleta2': boleta2})
            url = reverse('ventas:exito')
            return HttpResponseRedirect(url)

            #url = reverse('ventas:detalle_boleta', kwargs={'id': boleta2.id})
            #return HttpResponseRedirect(url)
        else:
                return render(request, 'ventas/verifica.html')
               
@login_required
def tipodocumento(request):
        if request.method == 'POST':
                tipo = request.POST['documento']
                if tipo == 'boleta':
                        nueva_boleta = Boleta(id_venta=Venta.objects.latest('id'))
                        nueva_boleta.save()                       
                        venta = Boleta.objects.latest('id').id_venta
                        print ("id de venta es " + str(venta))
                        #este te entrega el id producto y la cantidad a restar. 
                        detalles = DetalleVenta.objects.filter(id_venta=venta).values('id_producto','cantidad').count()
                        print("esto es el contador de objetos del queryset " + str(detalles))
                        
                        #este es para cargar todos los objetos de tipo detalleventa
                        
                        detalles = DetalleVenta.objects.filter(id_venta=venta).values('id_producto','cantidad')
                        print(detalles)
                        for detalle in detalles:
                        #instance.id_producto.stock += instance.cantidad
                                stock_actual=Producto.objects.get(id=detalle['id_producto']).stock
                                print(stock_actual)
                                #producto = Producto.objects.get(id=detalle['id_producto']).stock-=detalle['cantidad']
                                producto = Producto.objects.get(id=detalle['id_producto'])
                                producto.stock-=detalle['cantidad']
                                producto.save()
                        
###################################Como obtener el total de ventas################################################################                        

                        ventas=Boleta.objects.all().values('id_venta')
                        total=0
                        for venta in ventas:
                                sumando=Venta.objects.get(id=venta['id_venta']).total      
                                total = total + sumando
                        
                        print ('este es el total de venta: '+str(total))

                        return render(request, 'ventas/menu.html')
                else:
                        return render(request, 'ventas/verifica.html')

###################################################################################################################################
@login_required
def guardarfactura(request):
    if request.method == 'POST':
        nueva_factura = Factura(id_venta=Venta.objects.latest('id'), id_cliente=(request.POST['textinput']) )
        nueva_factura.save()

class VentaList(ListView):

    model = DetalleVenta
    context_object_name = 'venta_list'

    def get_queryset(self):
        return DetalleVenta.objects.filter(id_venta=Venta.objects.latest('id'))
        #template_name = 'ventas/VentaList.html'
    
    def get_context_data(self, **kwargs):

templates/ventas/2venta.html
{% extends "base.html"%}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-2">

        </div>
		<div class="col-md-8">
			<div class="row">
				<div class="col-md-2">
				</div>
				<div class="col-md-6">
                    <div id="espacio">&nbsp</div>
                    <div id="espacio">&nbsp</div>
							{{msj}}
                            <form class="form-row align-items-center " action="/ventas/nueva/add" method="POST">{% csrf_token %}
                                <label class="sr-only" for="textinput">Monto Inicial</label>
                                <input id="textinput" name="textinput" type="number" placeholder="Ingrese Codigo" class="form-control" required="">


				</div>
				<div class="col-md-4">
                    <div id="espacio">&nbsp</div>
                    <div id="espacio">&nbsp</div>
                    <button type="submit" class="btn btn-primary mb-1 ">Aceptar</button>
                    </form>
				</div>
			</div>
		</div>
		<div class="col-md-2">
		</div>
	</div>
</div>




{% endblock %}

templates/ventas/abrircaja.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}




<!-- <script type="text/javascript">   
    function Redirect() 
    {  
        window.location="/ventas/abrircaja"; 
    } 
    
    setTimeout('Redirect()', 2000);   
</script> -->

<div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                    <div class="alert alert-warning text-center" role="alert">
                            {{mesj}}
                    </div>
                <div class="row">    
                        <div class="col-md-8 offset-1">
                                <form class="form-row align-items-center" action="abrircaja" method="POST" >
                                    {% csrf_token %}
                                    <input type="number" class="form-control" id="monto" name="monto" placeholder="Monto inicial" required>
                    </div>
                        <div class="col-md-2">       
                            <button type="submit" class="btn btn-primary align-self-end">Enviar</button>
                        </div>
                    </form>
                    
                </div>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>

{% endblock %}

templates/ventas/cerrarcaja.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}




<div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
            {% if mesj %}
                    <div class="alert alert-warning text-center" role="alert">
                            {{mesj}}
                    </div>
            {% else %}
            &nbsp
            {% endif %}

            <div class="card">
				<h5 class="card-header">
					Cerrar Caja
				</h5>
				<div class="card-body">
					<div class="row">
                        <div class="col-md-3 text text-right offset-1">
                        Usuario:
                        </div>

                        <div class="col-md-7">
                            <input type="text" class="form-control form-control-sm" id="usuario" name="usuario" value = {{ usuario }} placeholder="{{ usuario }}" readonly>
                        </div>

                        <div class="col-md-3 text text-right offset-1">
                        Caja:
                        </div>

                        <div class="col-md-7">
                            <input type="text" class="form-control form-control-sm" id="caja" name="caja" value = {{ caja }} placeholder="{{ caja }}" readonly>
                        </div>

                        <div class="col-md-3 text text-right offset-1">
                        Fecha:
                        </div>

                        <div class="col-md-7">
                            <input type="text" class="form-control form-control-sm" id="fecha" name="fecha" value = {{ fecha }} placeholder="{{ fecha }}" readonly>
                        </div>

                        <div class="col-md-7 offset-1">
                                
                                <form class="form-row align-items-center" action="/ventas/cerrarcaja/" method='POST'>
                                    {% csrf_token %}
                                    
                        </div>
                        <div class="col-md-3">       
                            <button type="submit" class="btn btn-primary align-self-end">Enviar</button>
                        </div>
                                </form>
                    
                        </div>
				</div>
                
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>

{% endblock %}

<form class="form-row align-items-center" action="/ventas//" method='POST'>
                                    {% csrf_token %}

templates/ventas/detalleventa_list.html
{% load staticfiles %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="{%  static 'css/estilo.css '%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{%  static 'css/bootstrap.min.css '%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>OpenVendor POS</title>
</head>
<body>

<div class="container-fluid">
	<div class="row">
        <div class="col-md-1">
		</div>
		<div class="col-md-2 align-content-center">
            <div onclick="javascript:window.location.href='{% url 'abastecimiento:index'%}' ">
                <div class="navbar-brand align-content-center" href="/"><img src="{% static 'img/python.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">OpenVendor</div>
            </div>

		</div>
		<div class="col-md-3">
		</div>
		<div class="col-md-1">
		</div>
		<div class="col-md-1">
		</div>
		<div class="col-md-3">
		</div>
		<div class="col-md-1">
		</div>
		<div class="col-md-1">

		</div>
		<div class="col-md-2 ">
		</div>
		<div class="col-md-3 border border-0">

            <form class="form-row align-items-center text text-center text-black-50" action="/ventas/nueva/add" method="POST">
                {% csrf_token %}
                Codigo

                <input id="textinput" name="textinput" type="number" placeholder="Ingrese Codigo" class="form-control input-lg"
                       required="" autofocus >
		</div>

        <div class="col-md-1 text-black-50">
                Cantidad
                <input id="cantidad" name="cantidad" value="1" type="number" placeholder="1" class="form-control input-lg" autofocus >
		</div>

		<div class="col-md-1 text-light ">
            aceptar
                <button type="submit" class="btn btn-primary align-bottom"><span class="fa fa-barcode"></span> Aceptar</button>

		</div>
            </form>
		<div class="col-md-3 text text-center text-black-50 h-auto">
            <div class="text text-light">Total</div>
            <h2><strong>Total:</strong> {{suma}}</h2>


		</div>
		<div class="col-md-1">
		</div>
	</div>
	<div class="row">
		<div class="col-md-1">
		</div>
		<div class="col-md-2">
             <div class="list-group">
            <a><button type="button" onclick="window.location.href='{% url 'ventas:nueva' %}'" class="list-group-item list-group-item-action active">
             Nueva Venta
            </button></a>
            <a><button type="button" onclick="window.location.href='{% url 'ventas:cierracaja' %}'" class="list-group-item list-group-item-action" >Cerrar Caja</button></a>
            <button type="button" onclick="window.location.href='{% url 'abastecimiento:index' %}'" class="list-group-item list-group-item-action" >Menu Principal</button>
              
              
            
        </div>
		</div>
		<div class="col-md-5 border border-primary rounded">
            <table class="table text-center">
				<thead>
					<tr>
						<th>
							Producto
						</th>
						<th>
							Cantidad
						</th>
						<th>
							Precio
						</th>
					</tr>
				</thead>
                <tbody>
                {% for VentaList in object_list %}
                    <tr>
                        <td>{{VentaList.id_producto}}</td>
                        <td><center>{{VentaList.cantidad}}</center></td>
                        <td><center>{{VentaList.precio_venta_unitario}}</center></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

		<div class="col-md-3 rounded">
            <div class="card">
                <div class="card-header text-center">
                    <strong>Forma de Pago</strong>
                </div>
                <form class="form-row align-items-center" action="formapago" method="POST">{% csrf_token %}
                <div class="card-body">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
                        <label class="form-check-label" for="exampleRadios1">Efectivo</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2" disabled="disabled">
                        <label class="form-check-label" for="exampleRadios2">Tarjeta</label>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header text-center">
                    Documento
                </div>
                <div class="card-body">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="fp" id="exampleRadios3" value="boleta" checked>
                        <label class="form-check-label" for="exampleRadios3">Boleta</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="fp" id="exampleRadios4" value="factura" disabled>
                        <label class="form-check-label" for="exampleRadios4">Factura</label>
                    </div>
                </div>             
            </div>
            <div class="estilo">&nbsp</div>
            <input type="hidden" value={{suma}} name="suma" />
    			<button type="submit" class="btn btn-primary btn-lg btn-block">Siguiente</button>
        
        </form>
    </div>

		<div class="col-md-1">
		</div>
	</div>
</div>

</body>
</html>

templates/ventas/menu2.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}


    

<body>
  <div id="espacio">&nbsp</div>
  <div id="espacio">&nbsp</div>
  <div class="container">
    <h1></h1>
    <div class="row row-flex">
      <div class="col-md-4 col-sm-6 col-xs-12">
          <div onclick="javascript:window.location.href='{% url 'ventas:nueva' %}' ">
        <div class="content" style="background-color: #00CEC0">

            <img src="{% static 'img/venta.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="" /><h3>Ventas</h3>
          <p>Software POS</p>
        </div>
          </div>
      </div>
      <div class="col-md-4 col-sm-6 col-xs-12">
          <div onclick="javascript:window.location.href='{% url 'admin:abastecimiento_producto_changelist' %}' ">
            <div class="content" style="background-color:#F77D51">
                <img src="{% static 'img/producto.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="" /><h3>Productos</h3>
                <p>Lista de Productos</p>
            </div>
          </div>
      </div>
      <div class="col-md-4 col-sm-6 col-xs-12">
        <div onclick="javascript:window.location.href='{% url 'ventas:estadisticas' %}' ">
          <div class="content colour-3">
            <img src="{% static 'img/reporte.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="" /><h3>Reportes</h3>
          <p>Estadisticas y KPI de ventas</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 col-xs-12">
      <div onclick="javascript:window.location.href='{% url 'abastecimiento:compra' %}' ">
        <div class="content colour-4">
          <img src="{% static 'img/deal.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="" /><h3>Compras</h3>
          <p>Ingreso de Compras</p>
        </div>
      </div>
      </div>
      <div class="col-md-4 col-sm-6 col-xs-12">
        <div onclick="javascript:window.location.href='{% url 'abastecimiento:menu_buscar' %}' ">

            <div class="content colour-5">
                <img src="{% static 'img/existencias.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="" /><h3>Busqueda Producto</h3>
                <p>buscar codigo</p>
            </div>
        </div>
      </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <div onclick="javascript:window.location.href='{% url 'admin:index' %}' ">
                <div class="content colour-6">
                    <img src="{% static 'img/administracion.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="" /><h3>Administración</h3>
                    <p>Panel de Administración</p>
                </div>
                </div>
            </div>

    </div>
    
  
    
  </div>
</body>


{% endblock %}
{% block footer %}
{% endblock %}



    

templates/ventas/vista_factura.html
{% extends "base.html" %}

{% block tittle %}Facturas{% endblock %}

{% block content %}
    <div class="col-1"></div>
    <div class="col-10 offset-1">
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">venta</th>
      <th scope="col">forma de pago</th>
      <th scope="col">total</th>        
    </tr>
  </thead>
    <tbody>
      {% for fac in facturas %}
    <tr>
      <th scope="row"><a href="{% url 'ventas:detalle_factura' fac.factura__id %}">{{fac.factura__id}}</a></th>
      <td>{{fac.factura__id_venta}}</td>
      <td>{{fac.forma_pago}}</td>
      <td>{{fac.total}}</td>
    </tr>
      {% endfor %}
  </tbody>
</table>
</div>
    <div class="col-1"></div>
{% endblock %}