AMASADOSUR/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path, include
from ventas import views
from abastecimiento import views
from django import forms
from django.conf import settings
#from  import views


urlpatterns = [

    path(r'', views.index, name="index"),
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path(r'ventas/', include(('ventas.urls', 'ventas'), namespace='ventas')),
    path('admin/', admin.site.urls),
    path(r'abastecimiento/', include(('abastecimiento.urls', 'abastecimiento'), namespace='abastecimiento')),
    path(r'logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

]

ventas/urls.py
from . import views
from ventas import views
from django.urls import path, include

app_name='ventas'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'nueva/', views.nueva, name='nueva'),
    #path(r'nueva/boleta/', views.boleta, name='boleta'),
    path(r'nueva/add', views.detalleadd, name='add'),
    path(r'nueva/menu2/', views.menu2, name='menu2'),    
    path(r'abrircaja/', views.abrircaja, name='abrircaja'),
    path(r'nueva/lista/', views.VentaList.as_view(), name='ventalist'),

    path(r'nueva/lista/pagar', views.pagar, name='pagar'),
    path(r'nueva/lista/formapago', views.formapago, name='formapago'),
    #path(r'abrircaja/formapago', views.formapago, name='formapago'),
    #path(r'nueva/formapago', views.formapago, name='formapago'),
    path(r'nueva/lista/documento', views.tipodocumento, name='tipodocumento'),
    path(r'nueva/lista/verifica', views.verifica, name='verifica'),
    path(r'nueva/lista/registrocliente', views.registracliente, name='registracliente'),
    path(r'cerrarcaja/', views.cerrarcaja, name='cerrarcaja'),
    path(r'cerrarcaja/arqueo', views.arqueo, name='arqueo'),
    path(r'cierracaja/', views.cierracaja, name='cierracaja'),

    path(r'estadisticas/', views.estadisticas, name='estadisticas'),
    path(r'reporte/boletas/', views.vista_boleta, name='vista_boleta'),
    path(r'reporte/boletas/cierre', views.vista_boleta_vivo, name='vista_boleta_vivo'),
    path(r'reporte/facturas/', views.vista_factura, name='vista_factura'),
    path(r'reporte/boletas/detalle/<int:id>', views.detalle_boleta, name='detalle_boleta'),
    path(r'reporte/facturas/detalle/<int:id>', views.detalle_factura, name='detalle_factura'),
    path(r'exito/', views.exito, name='exito'),
    path(r'test/', views.test, name='test'),
    
]

    # path(r'reporte/boletas/lista', views.detalle_boleta, name='detalle_boleta'),

    # https://stackoverflow.com/questions/7217811/query-datetime-by-todays-date-in-django

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="es">
<head>
    {% block estilo %}
    <link rel="stylesheet" href="{%  static 'css/estilo.css '%}">
    {% endblock %}
    <link rel="stylesheet" href="{%  static 'css/bootstrap.min.css '%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{%  block tittle %} AmasadoSUR-Vendor {% endblock %}</title>
</head>
{% block menu %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <a class="navbar-brand" href="/"><img src="{% static 'img/python.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">OpenVendor</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/"><img src="{% static 'img/inicio.svg' %}" width="20" height="20" class="d-inline-block align-top" alt=""> Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{% static 'img/venta.svg' %}" width="20" height="20" class="d-inline-block align-top" alt="">
          POS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'ventas:nueva' %}">Nueva Venta</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item">Lista</a>
          <a class="dropdown-item" href="{% url 'ventas:vista_boleta' %}">--Boletas</a>
          <a class="dropdown-item" href="{% url 'ventas:vista_factura' %}">--Facturas</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'ventas:estadisticas' %}">Estadisticas</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Administración
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'ventas:abrircaja' %}">Abrir caja</a>
            <a class="dropdown-item" href="{% url 'ventas:cierracaja' %}">Cerrar caja</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'admin:index' %}">Administración</a>
      </li>
        {% if user.is_authenticated %}
    </ul>
      <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:logout' %}">Salir</a>
      </li>
    </ul>
      {% endif %}
  </div>
</nav>

{% endblock %}


{% block content %}
    <h5>Bloque de contenido</h5>
    
{% endblock %}










{% block footer %}
<nav class="navbar fixed-bottom navbar-light bg-light">
<div class="container justify-content-center">
{% load static %}
<a class="navbar-brand" href="https://www.djangoproject.com/"><img src="{% static 'img/django.png' %}" width="50" height="60" alt=""></a>
  <a class="navbar-brand " href="https://www.mysql.com/"><img src="{% static 'img/mysql.png' %}" width="60" height="70" alt=""></a>
  <a class="navbar-brand " href="https://www.w3.org/html/"><img src="{% static 'img/html5.png' %}" width="60" height="60" alt=""></a>
  <a class="navbar-brand" href="https://www.debian.org/index.es.html"><img src="{% static 'img/debian2.png' %}" width="45" height="65" alt=""></a>
  
</div>



</nav>
{% endblock %}

</html>

templates/index.html
{% extends "base.html" %}

templates/login.html
<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../../../favicon.ico">
  <title>OpenVendor</title> <!-- Bootstrap core CSS -->
  <link href="..\static\css\bootstrap.min.css" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="..\static\css\signin.css" rel="stylesheet">
</head>





<form class="form-signin" method="post">
  {% csrf_token %}
  
  <h1 class="h3 mb-3 offset-4 font-weight-normal">Ingresar </h1>
  <input type="text" name="username" required="required" class="form-control" placeholder="Username" />
  <input type="password" name="password" required="required" class="form-control" placeholder="Password" />
  <div class="checkbox mb-3">
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      Usuario o password no coincide
    </div>

    {% endif %}
    <label>
      <input type="checkbox" value="remember-me"> Recordar
    </label>
  </div>
  <button type="submit" class="btn btn-primary btn-lg btn-block">Aceptar</button>
  <p class="mt-5 mb-3 offset-3 text-muted">© 2018-2019</p>
</form>

<div id="extension-kmmojbkhfhninkelnlcnliacgncnnikf-installed"></div>
</body>

</html>